# Generated by Django 5.0.7 on 2024-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Diretor'), (2, 'Secretário'), (3, 'Professor'), (4, 'Aluno')], default=4),
        ),
    ]
